name = "%worker_name%"
main = "_worker.js"
compatibility_date = "2023-05-26"
routes = [
  { pattern = "%subdomain_name%", custom_domain = true },
  { pattern = "ava.game.naver.com.%subdomain_name%", custom_domain = true },
  { pattern = "blog.webex.com.%subdomain_name%", custom_domain = true },
  { pattern = "cdn.appsflyer.com.%subdomain_name%", custom_domain = true },
  { pattern = "investors.spotify.com.%subdomain_name%", custom_domain = true },
  { pattern = "investor.fb.com.%subdomain_name%", custom_domain = true },
  { pattern = "mssdk24-normal-useast2a.tiktokv.com.%subdomain_name%", custom_domain = true },
  { pattern = "zaintest.vuclip.com.%subdomain_name%", custom_domain = true }
  
]
workers_dev = false
[vars]
PASSWORD = "%password%"
PROXYIP = "%proxyip%"
DNS_RESOLVER_URL = "https://dns.cloudflare.com/dns-query"
